/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openni_java_PlaybackControl */

#ifndef _Included_openni_java_PlaybackControl
#define _Included_openni_java_PlaybackControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     openni_java_PlaybackControl
 * Method:    getSpeed
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_openni_java_PlaybackControl_getSpeed
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_PlaybackControl
 * Method:    setSpeed
 * Signature: (FJ)I
 */
JNIEXPORT jint JNICALL Java_openni_java_PlaybackControl_setSpeed
  (JNIEnv *, jobject, jfloat, jlong);

/*
 * Class:     openni_java_PlaybackControl
 * Method:    getRepeatEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_openni_java_PlaybackControl_getRepeatEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_PlaybackControl
 * Method:    setRepeatEnabled
 * Signature: (ZJ)I
 */
JNIEXPORT jint JNICALL Java_openni_java_PlaybackControl_setRepeatEnabled
  (JNIEnv *, jobject, jboolean, jlong);

/*
 * Class:     openni_java_PlaybackControl
 * Method:    seek
 * Signature: (Lopenni/java/VideoStream;IJ)I
 */
JNIEXPORT jint JNICALL Java_openni_java_PlaybackControl_seek
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     openni_java_PlaybackControl
 * Method:    getNumberOfFrames
 * Signature: (Lopenni/java/VideoStream;J)I
 */
JNIEXPORT jint JNICALL Java_openni_java_PlaybackControl_getNumberOfFrames
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     openni_java_PlaybackControl
 * Method:    isValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_openni_java_PlaybackControl_isValid
  (JNIEnv *, jobject, jlong);


#ifdef __cplusplus
}
#endif
#endif
