/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openni_java_CoordinateConverter */

#ifndef _Included_openni_java_CoordinateConverter
#define _Included_openni_java_CoordinateConverter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     openni_java_CoordinateConverter
 * Method:    convertWorldToDepth
 * Signature: (JFFFIIS)I
 */
JNIEXPORT jint JNICALL Java_openni_java_CoordinateConverter_convertWorldToDepth__JFFFIIS
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jint, jint, jshort);

/*
 * Class:     openni_java_CoordinateConverter
 * Method:    convertWorldToDepth
 * Signature: (JFFFFFF)I
 */
JNIEXPORT jint JNICALL Java_openni_java_CoordinateConverter_convertWorldToDepth__JFFFFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     openni_java_CoordinateConverter
 * Method:    convertDepthToWorld
 * Signature: (JIISFFF)I
 */
JNIEXPORT jint JNICALL Java_openni_java_CoordinateConverter_convertDepthToWorld__JIISFFF
  (JNIEnv *, jclass, jlong, jint, jint, jshort, jfloat, jfloat, jfloat);

/*
 * Class:     openni_java_CoordinateConverter
 * Method:    convertDepthToWorld
 * Signature: (JFFFFFF)I
 */
JNIEXPORT jint JNICALL Java_openni_java_CoordinateConverter_convertDepthToWorld__JFFFFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     openni_java_CoordinateConverter
 * Method:    convertDepthToColor
 * Signature: (JJIISII)I
 */
JNIEXPORT jint JNICALL Java_openni_java_CoordinateConverter_convertDepthToColor
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jshort, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
