/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openni_java_Device */

#ifndef _Included_openni_java_Device
#define _Included_openni_java_Device
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     openni_java_Device
 * Method:    open
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_openni_java_Device_open
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     openni_java_Device
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_openni_java_Device_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_Device
 * Method:    getDeviceInfo
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_openni_java_Device_getDeviceInfo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_Device
 * Method:    hasSensor
 * Signature: (IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_openni_java_Device_hasSensor
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     openni_java_Device
 * Method:    getSensorInfo
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_openni_java_Device_getSensorInfo
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     openni_java_Device
 * Method:    getPlaybackControl
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_openni_java_Device_getPlaybackControl
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_Device
 * Method:    setProperty
 * Signature: (IJIJ)I
 */
JNIEXPORT jint JNICALL Java_openni_java_Device_setProperty
  (JNIEnv *, jobject, jint, jlong, jint, jlong);

/*
 * Class:     openni_java_Device
 * Method:    isImageRegistrationModeSupported
 * Signature: (IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_openni_java_Device_isImageRegistrationModeSupported
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     openni_java_Device
 * Method:    getImageRegistrationMode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openni_java_Device_getImageRegistrationMode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_Device
 * Method:    setImageRegistrationMode
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_openni_java_Device_setImageRegistrationMode
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     openni_java_Device
 * Method:    isValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_openni_java_Device_isValid
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_Device
 * Method:    isFile
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_openni_java_Device_isFile
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_Device
 * Method:    setDepthColorSyncEnabled
 * Signature: (ZJ)I
 */
JNIEXPORT jint JNICALL Java_openni_java_Device_setDepthColorSyncEnabled
  (JNIEnv *, jobject, jboolean, jlong);

/*
 * Class:     openni_java_Device
 * Method:    isPropertySupported
 * Signature: (IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_openni_java_Device_isPropertySupported
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     openni_java_Device
 * Method:    invoke
 * Signature: (IJIJ)I
 */
JNIEXPORT jint JNICALL Java_openni_java_Device_invoke
  (JNIEnv *, jobject, jint, jlong, jint, jlong);

/*
 * Class:     openni_java_Device
 * Method:    isCommandSupported
 * Signature: (IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_openni_java_Device_isCommandSupported
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     openni_java_Device
 * Method:    Device
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_openni_java_Device_Device
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
