/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openni_java_VideoFrameRef */

#ifndef _Included_openni_java_VideoFrameRef
#define _Included_openni_java_VideoFrameRef
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     openni_java_VideoFrameRef
 * Method:    getDataSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openni_java_VideoFrameRef_getDataSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_VideoFrameRef
 * Method:    getData
 * Signature: (J)V
 */
JNIEXPORT jlong JNICALL Java_openni_java_VideoFrameRef_getData
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_VideoFrameRef
 * Method:    getSensorType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openni_java_VideoFrameRef_getSensorType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_VideoFrameRef
 * Method:    getVideoMode
 * Signature: (J)Lopenni/java/VideoMode;
 */
JNIEXPORT jlong JNICALL Java_openni_java_VideoFrameRef_getVideoMode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_VideoFrameRef
 * Method:    getTimestamp
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_openni_java_VideoFrameRef_getTimestamp
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_VideoFrameRef
 * Method:    getFrameIndex
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openni_java_VideoFrameRef_getFrameIndex
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_VideoFrameRef
 * Method:    getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openni_java_VideoFrameRef_getWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_VideoFrameRef
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openni_java_VideoFrameRef_getHeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_VideoFrameRef
 * Method:    getCroppingEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_openni_java_VideoFrameRef_getCroppingEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_VideoFrameRef
 * Method:    getCropOriginX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openni_java_VideoFrameRef_getCropOriginX
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_VideoFrameRef
 * Method:    getCropOriginY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openni_java_VideoFrameRef_getCropOriginY
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_VideoFrameRef
 * Method:    getStrideInBytes
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openni_java_VideoFrameRef_getStrideInBytes
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_VideoFrameRef
 * Method:    isValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_openni_java_VideoFrameRef_isValid
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_VideoFrameRef
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_openni_java_VideoFrameRef_release
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_VideoFrameRef
 * Method:    videoFrameRef
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_openni_java_VideoFrameRef_videoFrameRef
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
