/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openni_java_OpenNI */

#ifndef _Included_openni_java_OpenNI
#define _Included_openni_java_OpenNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     openni_java_OpenNI
 * Method:    initialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_openni_java_OpenNI_initialize
  (JNIEnv *, jclass);

/*
 * Class:     openni_java_OpenNI
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_openni_java_OpenNI_shutdown
  (JNIEnv *, jclass);

/*
 * Class:     openni_java_OpenNI
 * Method:    getVersion
 * Signature: ()Lopenni/java/JavaTypes/Version;
 */
JNIEXPORT jobject JNICALL Java_openni_java_OpenNI_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     openni_java_OpenNI
 * Method:    getExtendedError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_openni_java_OpenNI_getExtendedError
  (JNIEnv *, jclass);

/*
 * Class:     openni_java_OpenNI
 * Method:    enumerateDevices
 * Signature: (Lopenni/java/Array;)V
 */
JNIEXPORT void JNICALL Java_openni_java_OpenNI_enumerateDevices
  (JNIEnv *, jclass, jobject);

/*
 * Class:     openni_java_OpenNI
 * Method:    waitForAnyStream
 * Signature: ([Lopenni/java/VideoStream;III)I
 */
JNIEXPORT jint JNICALL Java_openni_java_OpenNI_waitForAnyStream
  (JNIEnv *, jclass, jobjectArray, jint, jint, jint);

/*
 * Class:     openni_java_OpenNI
 * Method:    addDeviceConnectedListener
 * Signature: (Lopenni/java/DeviceConnectedListener;)I
 */
JNIEXPORT jint JNICALL Java_openni_java_OpenNI_addDeviceConnectedListener
  (JNIEnv *, jclass, jobject);

/*
 * Class:     openni_java_OpenNI
 * Method:    addDeviceDisconnectedListener
 * Signature: (Lopenni/java/DeviceDisconnectedListener;)I
 */
JNIEXPORT jint JNICALL Java_openni_java_OpenNI_addDeviceDisconnectedListener
  (JNIEnv *, jclass, jobject);

/*
 * Class:     openni_java_OpenNI
 * Method:    addDeviceStateChangedListener
 * Signature: (Lopenni/java/DeviceStateChangedListener;)I
 */
JNIEXPORT jint JNICALL Java_openni_java_OpenNI_addDeviceStateChangedListener
  (JNIEnv *, jclass, jobject);

/*
 * Class:     openni_java_OpenNI
 * Method:    removeDeviceConnectedListener
 * Signature: (Lopenni/java/DeviceConnectedListener;)V
 */
JNIEXPORT void JNICALL Java_openni_java_OpenNI_removeDeviceConnectedListener
  (JNIEnv *, jclass, jobject);

/*
 * Class:     openni_java_OpenNI
 * Method:    removeDeviceDisconnectedListener
 * Signature: (Lopenni/java/DeviceDisconnectedListener;)V
 */
JNIEXPORT void JNICALL Java_openni_java_OpenNI_removeDeviceDisconnectedListener
  (JNIEnv *, jclass, jobject);

/*
 * Class:     openni_java_OpenNI
 * Method:    removeDeviceStateChangedListener
 * Signature: (Lopenni/java/DeviceStateChangedListener;)V
 */
JNIEXPORT void JNICALL Java_openni_java_OpenNI_removeDeviceStateChangedListener
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
