/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openni_java_DeviceInfo */

#ifndef _Included_openni_java_DeviceInfo
#define _Included_openni_java_DeviceInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     openni_java_DeviceInfo
 * Method:    getUri
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_openni_java_DeviceInfo_getUri
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_DeviceInfo
 * Method:    getVendor
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_openni_java_DeviceInfo_getVendor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_DeviceInfo
 * Method:    getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_openni_java_DeviceInfo_getName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_DeviceInfo
 * Method:    getUsbVendorId
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_openni_java_DeviceInfo_getUsbVendorId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_DeviceInfo
 * Method:    getUsbProductId
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_openni_java_DeviceInfo_getUsbProductId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_DeviceInfo
 * Method:    deviceInfo
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_openni_java_DeviceInfo_deviceInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
