/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openni_java_SensorInfo */

#ifndef _Included_openni_java_SensorInfo
#define _Included_openni_java_SensorInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     openni_java_SensorInfo
 * Method:    getSensorType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openni_java_SensorInfo_getSensorType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openni_java_SensorInfo
 * Method:    getSupportedVideoModes
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_openni_java_SensorInfo_getSupportedVideoModes
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
